### ISSUE TITLE
undefined local variable or method `b3'

### ISSUE THREAD

**Issue by herrbischoff** [jesa7955/vagrant-bhyve#7]
Running any `vagrant` command on FreeBSD 11.1 gets me the following error:

```
/usr/local/lib/ruby/gems/2.3/gems/vagrant-bhyve-0.1.0/lib/vagrant-bhyve/action.rb:51:in `block (3 levels) in action_halt': undefined local variable or method `b3' for VagrantPlugins::ProviderBhyve::Action:Module (NameError)
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/builtin/call.rb:47:in `call'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/builder.rb:116:in `call'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:66:in `block in run'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:66:in `run'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/builder.rb:116:in `call'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:66:in `block in run'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:66:in `run'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/builder.rb:116:in `call'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:66:in `block in run'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:66:in `run'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/builder.rb:116:in `call'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:66:in `block in run'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:66:in `run'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/builder.rb:116:in `call'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:66:in `block in run'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:66:in `run'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/machine.rb:227:in `action_raw'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/machine.rb:202:in `block in action'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/environment.rb:631:in `lock'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/machine.rb:188:in `call'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/machine.rb:188:in `action'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/plugins/commands/destroy/command.rb:31:in `block in execute'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/plugin/v2/command.rb:235:in `block in with_target_vms'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/plugin/v2/command.rb:229:in `each'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/plugin/v2/command.rb:229:in `with_target_vms'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/plugins/commands/destroy/command.rb:30:in `execute'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/cli.rb:42:in `execute'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/lib/vagrant/environment.rb:308:in `cli'
	from /usr/local/lib/ruby/gems/2.3/gems/vagrant-2.0.0/bin/vagrant:141:in `<top (required)>'
	from /usr/local/bin/vagrant:23:in `load'
	from /usr/local/bin/vagrant:23:in `<main>'
```

**Comment by herrbischoff** [comment]
Closing despite being unsolved, since this is obviously an abandoned project.
